### ISSUE TITLE
Add ability to add word to dictionary

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/spell-checker-addon#1]
Maybe devise a way to create a .bdic file or edit one?

**Comment by BlueGreenMagick** [comment]
Code to create a bdic file is in https://github.com/AnKing-Memberships/spell-checker-addon/blob/create-bdic/src/spell_checker/bdicwriter.py

Just need to incorporate this into the add-on.

**Comment by BlueGreenMagick** [comment]
Added with #4
