### ISSUE TITLE
As I understand it, this add-on still isn't completed yes?

### ISSUE THREAD

**Issue by imli700** [AnKing-VIP/spell-checker-addon#3]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Your question

Heya, is this add-on completed or is there a way to install that I'm not seeing?

**Comment by BlueGreenMagick** [comment]
It is still being worked on, but you can download it here: https://github.com/AnKing-Memberships/spell-checker-addon/releases

**Comment by imli700** [comment]
I see. Thanks a lot!

**Comment by zjosua** [comment]
Hi @BlueGreenMagick and @AnKingMed.
What features do you plan to implement before release?
I'd be happy to help out a little if you'll accept it.

**Comment by BlueGreenMagick** [comment]
I think the plan was to release as is, only fixing bugs when found. If you have any new features you want to implement, all contributions are welcome!

**Comment by AnKingMed** [comment]
Hoping to release it soon. I'm just waiting on the member of our team that's going to do that. We were going to release on our membership initially and then public but may just release public

**Comment by zjosua** [comment]
I see. Will the github repo remain public if you release for members only?

**Comment by AnKingMed** [comment]
yeah it'll remain public still
