### ISSUE TITLE
Rename addon within Anki

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/spell-checker-addon#5]
@BlueGreenMagick can we rename this addon within Anki so it doesn't confuse with the other spell checker addon? Could rename it "Spell Checker with Custom Dictionaries"

**Comment by AnKingMed** [comment]
Other updates we've already discussed

- [x] add the other dictionaries by default
- [x] change the menu to the anking menu
- [x] add dialog for people to add/remove words

**Comment by BlueGreenMagick** [comment]
Mostly finished. I think the only thing left is to update the README file.

Other features added:
[x] Bundled dictionary for anki terms (cloze fields 'c1::', '[sound:.mp3]', etc.)
